name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      node: ${{ steps.release-please.outputs['nipaw_node--release_created'] }}
      github: ${{ steps.release-please.outputs['nipaw_github--release_created'] }}
      gitee: ${{ steps.release-please.outputs['nipaw_gitee--release_created'] }}
      gitcode: ${{ steps.release-please.outputs['nipaw_gitcode--release_created'] }}
      cnb: ${{ steps.release-please.outputs['nipaw_cnb--release_created'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json


  publish-lib:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: ${{ needs.release.outputs.github || needs.release.outputs.gitcode || needs.release.outputs.gitee || needs.release.outputs.cnb }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 Rust 工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@v2

      - name: 发布nipaw_github
        if: needs.release.outputs.github
        run: |
          cargo publish --package nipaw_github
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_gitcode
        if: needs.release.outputs.gitcode
        run: |
          cargo publish --package nipaw_gitcode
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_gitee
        if: needs.release.outputs.gitee
        run: |
          cargo publish --package nipaw_gitee
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_cnb
        if: needs.release.outputs.cnb
        run: |
          cargo publish --package nipaw_cnb
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}


  build:
    needs: release
    if: needs.release.outputs.node
    uses: ./.github/workflows/build.yml

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    steps:
      - name: 下载npm包
        uses: actions/download-artifact@v5
        with:
          name: "npm-package"
          path: nipaw_node

      - name: 下载构建产物
        uses: actions/download-artifact@v5
        with:
          pattern: nipaw-node*
          path: nipaw_node/artifacts

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: nipaw_node
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
